rughh/on_ruby

- app/observers/cache_expiration.rb
> expires partials for es as well

- app/assets/stylesheets/application.sass
- app/helpers/external_link_helper.rb
- app/views/layouts/application.slim
as @plexus says: https://twitter.com/plexus/status/574864704197230592
> rgsoc donation hint

- config/whitelabel.yml
Hi there,
One of our sponsors requested us to include some tracking info on their link. Please merge and :ship: this when you can :)
> update madrid.rb sponsor url

- config/whitelabel.yml
As the title says, I updated to our new schedule and place. :smile:
> Updated RUGSaar for new place, contributors and dates

- app/models/material.rb
- app/models/topic.rb
- app/views/topics/_materials.slim
- app/views/topics/show.slim
- config/typus/material.yml
- db/migrate/20160217231126_attach_material_to_topic.rb
- db/schema.rb
- spec/views/topics/show.html_spec.rb
- Allows materials to be displayed on the topic page 
- Does not change behavior of existing materials 
This improves the ability to find topic related materials like links to slides etc.
> Attaches material to topic

- config/whitelabel.yml
> Change Colognerb Slack URL

- .travis.yml
- Gemfile
Hi @phoet, 
I saw, you're still running with Ruby 2.3.0, so I made very small changes to go with 2.3.1. 
Have an awesome evening. 👍 
Cheers
> Migrate to ruby 2.3.1

- Gemfile
- Gemfile.lock
> Revert "Upgrade uglifier to version 3.1.0"

- config/locales/es.yml
> add Spanish translation for 'flash.duplicate_nick'

- Dockerfile
upgrade the docker ruby version to match the required version
in the Gemfile
> Fix #259 Upgrade docker ruby version

- CONTRIBUTING.md
This may be a bit too high-level overview (it still makes a few assumptions about the knowledge of a potential contributor), but at least it's a start.
> Add instructions for potential contributors

- app/models/topic.rb
- spec/models/topic_spec.rb
> Remove uniqueness validation for topic name

- Gemfile
- Gemfile.lock
- app/models/material.rb
- spec/models/material_spec.rb
validation for material URLs to prevent wrong urls
solves issue #304
> feat: validate material urls #304

- Gemfile
- Gemfile.lock
- lib/tasks/data.rake
- spec/spec_helper.rb
- spec/support/factories/authorizations.rb
- spec/support/factories/events.rb
- spec/support/factories/highlights.rb
- spec/support/factories/jobs.rb
- spec/support/factories/likes.rb
- spec/support/factories/locations.rb
- spec/support/factories/materials.rb
- spec/support/factories/participants.rb
- spec/support/factories/topics.rb
- spec/support/factories/users.rb
because it's renamed and factory_girl is getting deprecated
see https://robots.thoughtbot.com/factory_bot
> chore: use factory_bot instead of factory_girl

- readme.md
This PR copy-edits small things in the README, adding formatting.
> README: polishing grammar

- readme.md
This PR tries to add information in the right order for a Docker installation.
> README: More details and sequence about Docker install

- app/views/home/_events.slim
- app/views/locations/none.de.slim
- config/locales/de.yml
- config/locales/en.yml
- config/locales/es.yml
linking to the none page when next meetup is not published yet
> add none when nothing setup

- db/old_migrations/20101217142810_create_histories_table.rb
> FIX index problem is too long limit 64 when run db:migrate

- app/controllers/home_controller.rb
- app/views/home/_locations.slim
- config/whitelabel.yml
- spec/views/home/index.html_spec.rb
Hi phoet, I would like use a customize zoom level.
Thanks a lot in advance
> fix zoom map to every Usergroup configuration into yml

- readme.md
> Fix typo in Readme

- app/controllers/admin/events_controller.rb
- app/dashboards/event_dashboard.rb
- app/dashboards/location_dashboard.rb
- app/dashboards/material_dashboard.rb
- app/dashboards/topic_dashboard.rb
- app/dashboards/user_dashboard.rb
- app/models/concerns/slug.rb
- No tests yet, I didn't have enough time to re-learn enough rspec to be able to add tests also there were no tests for the admin stuff before - My guess is that we probably want to change that but my focus right now is to make prod usable for organizers again.
- I just added enough config to fix the things I ran into when I tried to setup the Hamburg meeting. I will continue if y'all think this is the right direction
- I may have used opinionated defaults in some areas - I also didn't have time to set up a parallel instance with the old version and copying stuff over from there.
> Adding enough administrate configuration to make working with events bearable

- Gemfile
- Gemfile.lock
- app/models/usergroup.rb
- spec/models/usergroup_spec.rb
replace the magic calculation of next event date with a natural language parser, that is able to understand "second wednesday". 
Has some problems with last wednesday though, which might be the fourth or fifth wednesday depending on the month.
> replace recurring calculation with gem

- app/views/locations/none.en.slim
- app/views/locations/none.es.slim
- config/environments/development.rb
- config/locales/es.yml
Mainly I translate locations/none page
> spanish translations

- app/assets/stylesheets/application.sass
- app/helpers/link_helper.rb
- app/helpers/topics_helper.rb
- app/views/application/_headline.slim
- app/views/events/index.slim
- app/views/topics/show.slim
- spec/views/topics/show.html_spec.rb
reworking topic page https://github.com/phoet/on_ruby/issues/554
> Rework event page

- app/assets/stylesheets/application.sass
- app/helpers/link_helper.rb
- app/models/user.rb
- app/views/application/_nav.slim
- app/views/home/_topics.slim
- app/views/layouts/application.slim
- app/views/topics/show.slim
- app/views/users/show.slim
> Rework user page

- app/dashboards/location_dashboard.rb
- app/helpers/link_helper.rb
- app/views/locations/show.slim
- app/views/users/show.slim
> update location page

- app/assets/stylesheets/application.sass
- app/controllers/events_controller.rb
- app/controllers/home_controller.rb
- app/controllers/topics_controller.rb
- app/controllers/users_controller.rb
- app/helpers/events_helper.rb
- app/views/events/show.slim
- app/views/home/_events.slim
- app/views/home/_people.slim
- app/views/users/_list.slim
- app/views/users/index.slim
- config/initializers/kaminari_config.rb
> first throw at it

- app/assets/stylesheets/labels/barcelona.sass
- app/views/events/_info.slim
- app/views/users/_list.slim
- app/views/users/index.slim
Such wide monitors, such small columns, no longer!
> Display topics wider for Barcelona

- Dockerfile
- script/server
* add bundler 2
* fix host access to the container
> Docker access

- app/assets/javascripts/administrate/application.js
- app/assets/javascripts/administrate/components/date_time_picker.js
- app/assets/javascripts/administrate/components/has_many_form.js
- app/assets/javascripts/administrate/components/table.js
closes https://github.com/phoet/on_ruby/issues/610
> Fix administrate

- .rubocop.yml
- app/controllers/admin/users_controller.rb
- app/controllers/concerns/user_handling.rb
- app/controllers/super_admin/application_controller.rb
- app/controllers/super_admin/authorizations_controller.rb
- app/controllers/super_admin/events_controller.rb
- app/controllers/super_admin/highlights_controller.rb
- app/controllers/super_admin/jobs_controller.rb
- app/controllers/super_admin/likes_controller.rb
- app/controllers/super_admin/locations_controller.rb
- app/controllers/super_admin/materials_controller.rb
- app/controllers/super_admin/participants_controller.rb
- app/controllers/super_admin/topics_controller.rb
- app/controllers/super_admin/users_controller.rb
- app/dashboards/user_dashboard.rb
- config/routes.rb
closes https://github.com/phoet/on_ruby/issues/622 https://github.com/phoet/on_ruby/issues/623
in general this will be a first step into having properly scoped admin rights. it's far from perfect, as it will not prevent an admin from going from logging into another usergroup and editing or deleting stuff there, but it will reduce the risk of accidentally changing things in other usergroups
/cc @mediafinger
> split the admin views

- app/assets/stylesheets/application.sass
- app/helpers/link_helper.rb
- app/views/application/_nav.slim
- app/views/events/_info.slim
- app/views/events/_location.slim
- app/views/events/_materials.slim
- app/views/events/_participants.slim
- app/views/events/_topics.slim
- app/views/events/show.slim
- app/views/home/_events.slim
- app/views/home/_featured.slim
- app/views/home/index.slim
see also https://github.com/phoet/on_ruby/issues/554
> better feature the next event

- config/whitelabel.yml
Mit @cpetschnig und @knugie abgesprochen
> Change organizers of Leipzig on Rails

- app/helpers/ical_helper.rb
- spec/helpers/ical_helper_spec.rb
ups, we're communicating wrong start times with ical
> fix: correct ical start/end times

- app/controllers/admin/users_controller.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/controllers/super_admin/users_controller_spec.rb
As described by https://administrate-demo.herokuapp.com/customizing_controller_actions
> fix: scope user resource for admins

- app/controllers/concerns/locale_detection.rb
- spec/controllers/concerns/locale_detection_spec.rb
so far we ignore the browser provided list of user preferred locales. Maybe it's worth to respect the user hint?
> feat: detect browser locale

- .github/workflows/build.yaml
the pipleline did not run anymore since the actions we used are to old
> ci: fix outdated gh action
