- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.sass
- app/concerns/preview_generator.rb
- app/helpers/preview_helper.rb
- app/models/material.rb
- app/views/events/_materials.slim
- config/initializers/link_thumbnailer.rb
- db/migrate/20150203222133_add_preview_fields_to_material.rb
- db/schema.rb
- spec/concerns/preview_generator_spec.rb
- spec/helpers/preview_helper_spec.rb
- spec/models/material_spec.rb
This PR allows materials to generate a "preview" using [LinkThumbnailer](https://github.com/gottfrois/link_thumbnailer)
Often the previews are just images, but for the services which support [OpenGraph](http://ogp.me/) it can also generate embedded videos.
Here's how it looks:
Unfortunately some of the most popular websites (Youtube, Slideshare) don't follow OpenGraph, so you get an image for them instead (I [created an issue in LinkThumbnailer](https://github.com/gottfrois/link_thumbnailer/issues/51) in case there's something else that can be done). Vimeo happens to support it, so it looks very well, generating the embedded video right there. 
The PR adds two db fields to Materials, called `preview_type` and `preview_code` (note that you will need to migrate the db), which are …
> Materials Preview

- app/helpers/application_helper.rb
- app/helpers/events_helper.rb
- app/views/events/_materials.slim
- app/views/events/index.slim
- app/views/events/index.xml.builder
- app/views/events/show.slim
- app/views/home/_events.slim
- app/views/home/_locations.slim
- app/views/shared/_nav.slim
- config/locales/de.yml
- config/locales/en.yml
- config/locales/es.yml
This is related with #171 . It displays a webcal and rss link at the bottom of the Events#index view, like so:
Since I wanted the events-related i18n entries to be inside the `events` namespace, and there was an `events` string entry for the events I moved it (along with all the main "entities") inside a `main` namespace. I hope that's ok.
I also noticed some hardcoded German inside the rss feed. Since this feed is potentially available without logging in (and thus without a locale set up) I decided to change it so that it does not contain any language-specific idioms whatsoever.
EDIT: also moved link "Events I'm attending to" to Events#index (see updated screenshot above). I also added a couple links to "see all events".
> Show calendar in events index

- app/models/usergroup.rb
- app/views/home/_events.slim
- config/locales/de.label.yml
- config/locales/en.label.yml
- config/locales/es.label.yml
- config/whitelabel.yml
- spec/models/usergroup_spec.rb
for complicated cases, allow a usergroup to specify a custom recurrence using a translated string, which will be displayed on the homepage instead of a calculated next event date.
> allow custom recurrence

- config/locales/es.yml
Removes the redundant word 'sitios' (home.usergroup_locations), since 'Lugares' (main.locations) is already added within the location_link.
> Fix typo @ 'usergroup_locations' in Spanish locale file

- app/controllers/home_controller.rb
- app/controllers/topics_controller.rb
- app/models/topic.rb
- app/views/home/_topics.slim
- app/views/home/index.slim
- app/views/topics/_upcoming.slim
- config/locales/de.yml
- config/locales/en.yml
- config/locales/es.yml
- spec/views/home/index.html_spec.rb
If a topic is assigned to an event, the topic currently appears under 'Recent Topics' even if the event is in the future. In my opinion, this is misleading since the topic has not been presented yet.
This pull request adds another subsection for upcoming topics to the 'Topics' section. What do you think about this? In particular:
* Is the extra subsection 'Upcoming Topics' reasonable, or should we merge the upcoming topics into the existing 'Proposals' subsection? 
* What about the order of subsections? This code uses 'Upcoming Topics', 'Proposals', 'Recent Topics' - but we might as well go for 'Proposals', 'Upcoming Topics', 'Recent Topics'.
* I had to use google translate for the spanish translation - can anyone who speaks spanish double check the wording?
The implemantion relies on …
> upcoming topics should not appear as 'Recent Topics'

- .travis.yml
According to the [Travis Docs](http://docs.travis-ci.com/user/docker/),
we could also build with `language: ruby` but I think we should stay in
container-county, as everyone will execute tests this way.
> Build with docker-compose on Travis (refs #191)

- app/models/event.rb
In Cologne we have bi-monthly meetups and the next event (on January 20 http://www.colognerb.de/events/januar-2016-meetup) is currently not yet displayed on our homepage http://www.colognerb.de/ because the search period is too short. This should fix that.
Thanks.
> Increase search period for current event

- app/helpers/external_link_helper.rb
- app/models/usergroup.rb
- app/views/home/_people.slim
- config/whitelabel.yml
We have now one slack group for all onruby members/groups. I added a
invite box/badge, provided by slackin, to the application because it's only
possible to join the slack group by an invite.
> Add slackin to the index page and also to the people section

- app/views/users/edit.slim
I just found out that my url is not editable. I added the field to the form. 
Warning: I could not test it this morning because I could not setup the twitter / github login locally.
> make url editable

- config/whitelabel.yml
Update imprint from 
`Amalienstraße 44 
76133 Karlsruhe `
to
`Haid-und-Neu-Str. 18 
76131 Karlsruhe `
> Update imprint of NinjaConcept GmbH

- .gitignore
`.ruby-gemset` is already ignored and the repository doesn't itself contain `.ruby-version` file. I believe that it makes sense to ignore `.ruby-version` file as well.
> Add .ruby-version file to .gitignore

- app/controllers/participants_controller.rb
- spec/controllers/participants_controller_spec.rb
The ParticipantsController did not use the new slug handling code to find
events so the participate button was broken.
> Fix ParticipantsController not finding events

- app/models/location.rb
- app/models/usergroup.rb
- config/locales/de.yml
- config/whitelabel.yml
- spec/models/location_spec.rb
- spec/support/factories/locations.rb
looking at the [current madridrb](http://www.madridrb.com/events/septiembre-2017-409) event i noticed that the location was off on the map.
digging around a bit i noticed that 
* we have an issue with reaching the API limit for geo-coder (have not investigated why)
* there is static data when creating the geocoding address
i fixed the latter, so we can actually geo-code none german locations properly.
> actually make the country dynamic

- lib/tasks/scheduler.rake
I've noticed a small issue with the descriptions within the scheduler rake tasks file
now both tasks will also be listed then listing rake tasks:
```bash
[...]
rake scheduler:update_geocoding         # update geocoding
rake scheduler:update_preview           # update previews
[...]
```
> docs: correct descriptions for scheduler rake tasks

- app/controllers/admin/users_controller.rb
- app/extensions/typus/authentication/custom.rb
- spec/controllers/admin/users_controller_spec.rb
in order to fix #291 this 
a) hides the user creation action by overwriting the new action in the users admin controller
b) hardcodes the rule the user create action is disallowed
/cc @emrox
> Disable creating users from the admin

- readme.md
> New slack location as channel within ruby berlin

- app/models/usergroup.rb
- app/views/labels/index.slim
- app/views/shared/_footer.slim
- config/whitelabel.yml
- readme.md
as i'm currentyl phasing out the onruby.at domain, i noticed that insbruck has never once scheduled a meetup. 
looking through some of the other usergroups it looks like they are not using unruby any longer or are completely gone.
because of this i added a status, disabling all groups that did not have once scheduled an event within 2017.
> remove unused usergroups

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
Currently user input in the user profile description is not sanitized and allows arbitrary HTML including script tags.
> sanitize html in markdown content

- config/locales/en.yml
Just a minor text improvement.
> Use plural for location link in en.yml

- docker-compose.yml
- readme.md
- script/open
the Dockerfile was outdated and did not bind to the proper port of puma 3000
with the proper etc hosts settings i was able to load `http://hamburg.onruby.test:3000/` from the docker image.
`docker ps` should show that everything is up and running
```
→ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
b14a5d553f0e        on_ruby_web         "/bin/sh -c script/s…"   3 minutes ago       Up 3 minutes        0.0.0.0:3000->3000/tcp   on_ruby_web_1
7d02676cf2e4        postgres:9.4.1      "/docker-entrypoint.…"   7 minutes ago       Up 3 minutes        5432/tcp                 on_ruby_postgres_1
```
closes #457
> Fix docker port binding

- app/controllers/users_controller.rb
- app/helpers/external_link_helper.rb
- app/views/users/edit.slim
- app/views/users/show.slim
- db/migrate/20180913110659_add_linkedin_to_users.rb
- db/schema.rb
- spec/controllers/users_controller_spec.rb
- spec/helpers/external_link_helper_spec.rb
Development to update and close the #435 new feature.
The user profile can now optionally have a linkedin field.
Tests have been added in the following spec sections.
spec/controllers/users_controller_spec.rb:75
spec/helpers/external_link_helper_spec.rb:25
script/in_docker bundle exec rspec ./spec/controllers/users_controller_spec.rb:75
script/in_docker bundle exec rspec ./spec/helpers/external_link_helper_spec.rb:25
(run script/in_docker bundle exec rake db:test:prepare before running, as their is a new migration for user_profile linkedin). 
Deployment will need a rake db:migration 
Work by @alterisian and @Adsidera after surveying the RUG B mailing list indicated a need for this feature from a significant proportion of respondents.
> LinkedIn Field and tests added

- Gemfile
- Gemfile.lock
- app.json
- app/controllers/admin/events_controller.rb
- app/views/admin/dashboard/_sidebar.slim
- config/initializers/zero_push.rb
- config/routes.rb
- spec/controllers/admin/events_controller_spec.rb
This PR removes the ability to send iOS Push Notifications. The iOS app is no longer available in the store.
> iOS push notifications removed

- config/whitelabel.yml
Thx to @lukad for noticing.
See https://twitter.com/cocoaheads_hh
Rughh on premise hotfixes ftw.
> Fix cocoaheads twitter handle

- app/controllers/admin/application_controller.rb
- app/dashboards/event_dashboard.rb
- app/helpers/external_link_helper.rb
- app/models/usergroup.rb
- app/views/admin/events/show.html.erb
- app/views/events/show.slim
- app/views/shared/_footer.slim
- config/whitelabel.yml
- db/migrate/20190515101441_add_github_issue_to_event_and_topic.rb
- db/schema.rb
- spec/helpers/external_link_helper_spec.rb
https://github.com/phoet/on_ruby/issues/253
> add github references to planning issues

- spec/support/factories/events.rb
- spec/support/factories/highlights.rb
- spec/support/factories/materials.rb
- spec/support/factories/topics.rb
To avoid deprecation warnings when running `rake data:create` like this one:
_Passing `number` with the 1st argument of `words` is deprecated. Use keyword argument like `words(number: ...)` instead._
> Update factories to keyword arguments

- config/environments/development.rb
Rails 6 introduced this check:
https://www.fngtps.com/2019/rails6-blocked-host/
> Allow all .onruby.test domains in development

- app/models/usergroup.rb
That was missing to enable a smooth experience setting up a new user group
> Fix rake fork by adding canonical_url to Usergroup.from_name

- config/routes.rb
Ok, I would understand if someone that used the onruby/admin for years already would oppose this change. 😉 
But after using the admin section for half day, I am convinced the items I will use most often are:
* events
* locations
* topics
therefore I added those three on top. Followed by:
* materials (as this directly interacts with topics)
* highlights
* jobs
And the last items are the 4 global ones, that deal with users and their interactions:
* authorizations
* likes
* participants
* users
While this change might be seen controversial, I am convinced it is an improvement.
> Sort administrate menu

- app/helpers/link_helper.rb
- app/views/application/_hint.slim
At the moment jobs are not displayed at the top of the page, when a highlight is active. I don't know if this was a design decision at some point, but I'd argue we should always display the (few) jobs we have on the page.
When there is only one job offer, the chevron is not displayed anymore.
This change also opens linked pages of highlights, jobs descriptions and locations in a new tab.
> Display jobs also when a highlight is active

- app/assets/stylesheets/labels/barcelona.sass
The last PR went not fast enough, as it ignored how bootstrap's responsiveness works on smaller screens.
The new behavior (for event's topics of Barcelona only) is now, that on big screens always two topics will be displayed besides each other, while on smaller screens (like mobile phones) each topic gets the full width available. The breakpoint from 1 to 2 columns is deliberately late at around 1000px screen-width, as the topic box can only use around half of that in the current design.
> Fix mobile view of Barcelona's topics

- app/assets/stylesheets/application.sass
- app/views/events/index.slim
When browsing our RUG::B talk archive, something seemed a bit off with the way talks were displayed underneath events. Looks like it was a SLIM indention error.
When checking for how my "fix" looked mobile, I came across another issue with very long talk titles (unlikely to happen IRL) and tried to provide a fix for this by adding a `word-break` rule.
Please see attached screenshots for details and let me know what you think!
**Event page before changes**
**Event page after changes**
**Mobile home page before changes**
**Mobile home page after changes**
> Fix events talk list indention & add word-break to section lists

- config/whitelabel.yml
Hello, Madrid.rb has a new organizer.
His name is **Josep Egea Sánchez**. He already has an account in onruby.
* on_ruby nickname: josep_egea
* on_ruby id: /admin/users/josep_egea-1406
In addition of merging this PR, I would like to request the following
changes:
* That Josep's user account is promoted to administrator of the
Madrid.rb group
* That Josep's Github account (@josepegea) is given the same access to
the on_ruby github repository that I (kikito) currently possess.
* That my accounts (on_ruby: kikito-1369 / github: kikito)
are downgraded to match.
There's proof that this request is legitimate (and my account has not
been hacked) in the Madrid.rb mailing list, where I make the
announcement (it is in Spanish, but a Google translate should do): …
> Madrid.rb new organizer

- app/dashboards/event_dashboard.rb
- app/dashboards/location_dashboard.rb
- app/helpers/events_helper.rb
- app/models/location.rb
- app/views/events/_badges.slim
- app/views/events/_info.slim
- app/views/events/_location.slim
- app/views/locations/show.slim
- config/locales/de.yml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pl.yml
- db/migrate/20210113033955_add_virtual_locations.rb
- db/schema.rb
- spec/controllers/events_controller_spec.rb
- spec/models/location_spec.rb
- spec/support/factories/events.rb
- spec/support/factories/locations.rb
- spec/views/events/_info.html_spec.rb
- Added a 'virtual' flag for locations. If true, geographic attributes
are not mandatory and geocoding is not performed upon object save.
- Added a 'remote_url' attribute to events. If present, only for users
that have confirmed they will attend the event, a "Connect Remotely"
button will appear in the event page.
With so many remote events, due to Covid-19, it's a good thing that we
don't have to add fake geo data to locations (streen, city,
lat/long...) Showing maps in the site for remote events is confusing.
In addition, each event can have a unique remote URL (like a Google
Meet or Zoom URL).
In this way, a virtual location can have a global URL (like the Twitch
page for the usergroup) and each event can have its own remote
URL (only useful during the event).
Hoping that you find …
> Add virtual locations and remote links for events

- config/whitelabel.yml
Also, most of the sponsors still had non-https URLs but they have
already moved to https, so we updated them, too
> Move canonical URL for Madrid.rb to https

- config/whitelabel.yml
Hi, I'm not really involved anymore in the ruby user group in Leipzig. I want to remove myself from the list.
Thanks
> Remove tmetzmac from Leipzg as organizer

- config/whitelabel.yml
Weil heruko sein free tier abgeschaltet hat dieses Jahr haben wir unseren slackin auf fly.io umgezogen und ich würde gerne einmal die URL hier updaten.
> Update colognerb slackin_url

- app/assets/stylesheets/labels/cologne.sass
Hi @phoet! 👋 
The cologne user group is waking up and some members noted that they would prefer fewer beer glasses spilling over the content on mobile devices 😄
> don't spill :beer: over content on too small screens

- config/whitelabel.yml
Therefore that I'm joining the orga team for the Hamburg Usergroup, I thought it would be a good idea to add me to the organizer list
> add new organizer to Hamburg whitelabel

- app/helpers/application_helper.rb
- config/environments/development.rb
- lib/tasks/data.rake
- lib/tasks/fork.rake
- readme.md
As described in https://www.rfc-editor.org/rfc/rfc6761#section-6.3, anything "ending" with .localhost is considered localhost, so we can use http://$label.onruby.localhost:3000 for development purposes without changing /etc/hosts at all.
unless we want to develop with safari, which doesn't support this right now.
> chore: replace /etc/hosts change with RFC6761 localhost

- app/controllers/images_controller.rb
> fix: Kernel#open for URL got deprecated with 2.7

- config/database.yml
- docker-compose.yml
- readme.md
I had this files unchanged from the last testing session. Maybe it would be usefull for everyone. Thanks to @salzig for most of the changes.
> Update the development setup

- app/views/admin/events/show.html.erb
After saving an event, an error is displayed. This error occurs on the show page of the event. It seems that the administrate api has changed and the attributes are now nested in a hash with no given key.
This commit returns the correct attributes for the show page and resolves the attributes correctly.
Before:
After:
> fix: changed administrate api

- config/whitelabel.yml
I think all the three names are wrong, in the config. I fixed the one I know the other two aren't signed up. This way there is at least one Organizer visiable.
> fix: change the name of one of the dresdenrb organizers to the nickname

- config/puma.rb
This adds the appsignal plugin to puma. This way we build up metrics to our puma server in cases we need to profile or debug something puma worker related.
> chore: add appsignal plugin to puma

- app/models/authorization.rb
- readme.md
- spec/models/authorization_spec.rb
- spec/spec_helper.rb
One possible solution for #1063
As described in the issue mentioned above, with Twitter shutting down our authentication, users that only had that login configured are left out and cannot login. They can try to use different methods, but that means creating a new user.
One suggestion has been to add a new OAuth method based on OTP by email, which seems quite useful, but, still, wouldn't allow these users to connect to their old account.
As a special treatment for these special situation, this PR tries to allow these users to connect to their existing accounts if they log in using a different OAuth method and emails match.
The exact behaviour is:
1. If a new session successfully authenticates using a provider that includes email as part of their info.
2. If a user (and only one user) …
> Allow login for old Twitter users with same email

- app/models/user.rb
- spec/controllers/users_controller_spec.rb
After merging #1068 there's been some errors in AppSignal when trying to show the user page for users without email
This should fix them
> FIX: users#show crashing for users without email

- app/helpers/ical_helper.rb
- spec/helpers/ical_helper_spec.rb
RFC-5545 Section 3.3.5. requires UTC timestamps to end with Z to not be considered a floating timestamp.
https://www.rfc-editor.org/rfc/rfc5545#section-3.3.5
> fix: mark ics start and end time as non floating

- app/models/user.rb
Every User Card checks if the currently displayed user is one of the organisers to show the organiser badge. Before we used the Scope which fetches the User Objects matching the Organizer Nicknames to check if the current user is in that list. After we check if the current user nickname is part of the Organizer Nicknames, without asking the database for the users. 
Edit:
shaves off about 0.3ms per user attending.
> perf: skip roundtrip via database for organizers predicate

- config/locales/de.label.yml
- config/locales/en.label.yml
- config/locales/es.label.yml
- config/locales/pl.label.yml
This adds the custom recurrence text to other translations as they were previously inside the "meta_desc" translation and updates the text to reflect the three months meetup cycle that we plan to achieve.
The translations were done using deepl, so I hope they are fine.
> Update custom occurence for dresdenrb

- Gemfile
- Gemfile.lock
from kgio README
```
= kgio - a legacy I/O library that did a decade of damage to Ruby
This is a legacy project has discouraged improvements to Ruby itself.
It has done a decade of harm to Ruby and continues to harm it by being
used by (unfortunately) popular projects.  Ruby 2.3 and later makes
this obsolete.  kgio provides non-blocking I/O methods for Ruby without
raising exceptions on EAGAIN and EINPROGRESS.
```
> chore: remove kgio gem

- Gemfile
- Gemfile.lock
Legacy Gem, from README (already fulfilled for us): 
You can remove this gem after making sure the following sections are added in
your `production.rb` file:
**`config/environments/production.rb`**
```ruby
config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?
if ENV["RAILS_LOG_TO_STDOUT"].present?
logger           = ActiveSupport::Logger.new(STDOUT)
logger.formatter = config.log_formatter
config.logger = ActiveSupport::TaggedLogging.new(logger)
end
```
Make sure to add both the `RAILS_SERVE_STATIC_FILES` and `RAILS_LOG_TO_STDOUT` ENV vars and set them to `true`. (This is done for you on Heroku)
> chore: remove rails_12factor

- app/controllers/home_controller.rb
at least for the start page. Locations Page still shows all locations.
> feat: limit locations to since beginning of two years ago

- config/whitelabel.yml
Since we revived the Madrid.rb group by the end of last year, we are updating the sponsors
> chore: Update Madrid.rb sponsors

- app/models/event.rb
- app/models/highlight.rb
- spec/models/event_spec.rb
Let me know if you like the change or not. We already discussed a bit in #1084 and I feel like the artificial limit does not make much sense. If you feel like this changes behavior too much though, feel free to close this. I just had some free time and figured I create a PR for this to move forward. Maybe another solution would be better or maybe we don't want to change this at all.
This change removes the restriction of the current event to be at most 9 weeks in the future. Some user groups might decide to hold meetups less frequently so this limitation prevents them from advertising their next event until 9 weeks before the meetup.
With this change the current event that is displayed on the homepage will always be the next event, even if it's set far in the future.
Closes #1084
> Use next event as the "current" event
